Complete the archive-backport workflow
ubuntu-openstack/artifact-pipeline pull request #1
Opened 2023-12-01 21:04 UTC by coreycb

The archive-backport workflow is now functional, allowing for backporting an individual package to the cloud archive staging PPA for the specified OpenStack series.

Additionally, this change includes:
* README updates
* Switch to temporal logging
* Addition of utils.py that includes common code
* Add black formatter and formatted code with it
* Fix some mypy errors. There are several more to fix.

2023-12-04 13:14 UTC, freyes commented
wow, this is a great PR, Corey, I will review it.

PS: be aware there are mypy errors. The error in "snapcraft build" is not related to this PR.

2023-12-12 13:47 UTC, freyes requested changes
I went through this PR and there is a lot of great changes, Corey, much appreciated. I added one inline comment that's worth of discussing.

2023-12-12 13:47 UTC, freyes commented on artifact_pipeline/workflows/archive_backport.py
> +        if not retcode:
I'm thinking this `if` should have an `else` that bubbles up the failure so the workflow is marked as failed/error

```
if not code:
    ...
else:
    raise PreparePackageError(cmd, retcode, output)
```

we can follow the same pattern for the other if statements with specialized exceptions: `BuildPackageError`, `SignPackageError` and `UploadPackageError`.

We can then make Temporal to retry on certain class of errors (e.g. on `UloadPackageError` since it could be related to a transient networking error.)

2023-12-12 13:47 UTC, freyes commented on tox.ini
> +[testenv:black]
let's include `black` in the `envlist` at the top, so contributors running `tox` (without arguments) can get the results of black and avoid being surprised later at the CI.

2023-12-12 13:48 UTC, freyes requested changes
There is a build failure on the snap which we can ignore (it's a python-apt version failure), although the mypy failures should be solved - https://github.com/ubuntu-openstack/artifact-pipeline/actions/runs/7065282578/job/19234974867?pr=1

2023-12-12 15:01 UTC, coreycb commented
Thanks for reviewing Felipe. Would you mind if I address your comments in https://github.com/ubuntu-openstack/artifact-pipeline/pull/2 ? It has the same base commit that you reviewed here, with a backport-o-matic commit on top of it. I've addressed all the mypy failures in the b-o-m commit.

2023-12-12 17:39 UTC, freyes commented
Yeah, I don't mind. I will review that one now.

On Tue, 2023-12-12 at 07:01 -0800, coreycb wrote:
> Thanks for reviewing Felipe. Would you mind if I address your comments in #2 ? It has the same
> base commit that you reviewed here, with a backport-o-matic commit on top of it. I've addressed
> all the mypy failures in the b-o-m commit.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.Message ID:
> ***@***.***>

-- 
Felipe Reyes
Software Engineer @ Canonical
***@***.*** (GPG:0x9B1FFF39)
Launchpad: ~freyes | IRC: freyes

2023-12-14 21:37 UTC, coreycb commented on artifact_pipeline/workflows/archive_backport.py
> +        if not retcode:
I've been thinking about this and I like the idea. Though I have to admit this is an area where I wrestle with the smarts of temporal vs the needs of the backport tooling. For the 2 backport workflows that are up for review, the results get presented to the user and it's not an issue if they fail. backport-o-matic is a cron job so it'll retry on a future run. backport-package is run manually, so the user can retry after they see the results. This might be something we could add in the future.

2024-01-02 23:34 UTC, merged